/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tictac;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class MultiPlayerGame extends javax.swing.JFrame {

    /**
     * Creates new form Tic
     */
    ImageIcon cross;
    ImageIcon ovel;
    ImageIcon box;
    Players player;
    String player1Name;
    String player2Name;
    
    int player1score,player2score;
    public MultiPlayerGame() {
        
       
    }
    public MultiPlayerGame(String player1Name, String Player2Name){
        initComponents();
        setLocation(500, 200);
        cross=new ImageIcon("Cross.png");
        ovel=new ImageIcon("oo.png");
        box=new ImageIcon("t.png");
        player=new Players();
       this.player1Name=player1Name;
       this.player2Name=Player2Name;
       player2score=0;
       player1score=0;
       name1.setText(player1Name);
       name2.setText(Player2Name);
       score1.setText(String.valueOf(player1score));
       score2.setText(String.valueOf(player2score));
       
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        but1 = new javax.swing.JButton();
        but2 = new javax.swing.JButton();
        but3 = new javax.swing.JButton();
        but4 = new javax.swing.JButton();
        but5 = new javax.swing.JButton();
        but6 = new javax.swing.JButton();
        but7 = new javax.swing.JButton();
        but8 = new javax.swing.JButton();
        but9 = new javax.swing.JButton();
        name1 = new javax.swing.JLabel();
        name2 = new javax.swing.JLabel();
        ResetButton = new javax.swing.JButton();
        exitButton = new javax.swing.JToggleButton();
        score1 = new javax.swing.JLabel();
        score2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Papyrus", 1, 36)); // NOI18N
        jLabel1.setText("Tic Tac Toe");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 20, 280, 90);

        but1.setBackground(new java.awt.Color(204, 204, 204));
        but1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        but1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but1ActionPerformed(evt);
            }
        });
        jPanel1.add(but1);
        but1.setBounds(40, 110, 75, 75);

        but2.setBackground(new java.awt.Color(204, 204, 204));
        but2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        but2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but2ActionPerformed(evt);
            }
        });
        jPanel1.add(but2);
        but2.setBounds(120, 110, 75, 75);

        but3.setBackground(new java.awt.Color(204, 204, 204));
        but3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        but3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but3ActionPerformed(evt);
            }
        });
        jPanel1.add(but3);
        but3.setBounds(200, 110, 75, 75);

        but4.setBackground(new java.awt.Color(204, 204, 204));
        but4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        but4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but4ActionPerformed(evt);
            }
        });
        jPanel1.add(but4);
        but4.setBounds(40, 190, 75, 75);

        but5.setBackground(new java.awt.Color(204, 204, 204));
        but5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        but5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but5ActionPerformed(evt);
            }
        });
        jPanel1.add(but5);
        but5.setBounds(120, 190, 75, 75);

        but6.setBackground(new java.awt.Color(204, 204, 204));
        but6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        but6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but6ActionPerformed(evt);
            }
        });
        jPanel1.add(but6);
        but6.setBounds(200, 190, 75, 75);

        but7.setBackground(new java.awt.Color(204, 204, 204));
        but7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        but7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but7ActionPerformed(evt);
            }
        });
        jPanel1.add(but7);
        but7.setBounds(40, 270, 75, 75);

        but8.setBackground(new java.awt.Color(204, 204, 204));
        but8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        but8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but8ActionPerformed(evt);
            }
        });
        jPanel1.add(but8);
        but8.setBounds(120, 270, 75, 75);

        but9.setBackground(new java.awt.Color(204, 204, 204));
        but9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        but9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but9ActionPerformed(evt);
            }
        });
        jPanel1.add(but9);
        but9.setBounds(200, 270, 75, 75);

        name1.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        name1.setText("                    ");
        name1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(name1);
        name1.setBounds(300, 140, 100, 30);

        name2.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        name2.setText("                    ");
        name2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(name2);
        name2.setBounds(300, 200, 100, 30);

        ResetButton.setBackground(new java.awt.Color(0, 0, 0));
        ResetButton.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        ResetButton.setForeground(new java.awt.Color(65, 177, 230));
        ResetButton.setText("Reset");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ResetButton);
        ResetButton.setBounds(50, 360, 110, 30);

        exitButton.setBackground(new java.awt.Color(0, 0, 0));
        exitButton.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        exitButton.setForeground(new java.awt.Color(65, 177, 230));
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(exitButton);
        exitButton.setBounds(180, 360, 100, 30);

        score1.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        score1.setText("                    ");
        score1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(score1);
        score1.setBounds(420, 140, 60, 30);

        score2.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        score2.setText("                    ");
        score2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(score2);
        score2.setBounds(420, 200, 60, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictac/tumblr_static_elsa.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(4, 4, 520, 410);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 510, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int count=0;
    ImageIcon icon1;
    
    private void but1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but1ActionPerformed
        // TODO add your handling code here:
        
        if(count%2==0 && but1.getIcon()==null){
        but1.setIcon(ovel);
        }
        else if(but1.getIcon()!=null){
            count--;
        }
        
        else if(but1.getIcon()==null) {
            but1.setIcon(cross);
        }
        count++;
        select();
        
    }//GEN-LAST:event_but1ActionPerformed

    private void but2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but2ActionPerformed
        // TODO add your handling code here:
         if(count%2==0 && but2.getIcon()==null){
        but2.setIcon(ovel);
        }
        else if(but2.getIcon()!=null){
            count--;
        }
        else if(but2.getIcon()==null){
            but2.setIcon(cross);
        }
        count++;
        select();
    }//GEN-LAST:event_but2ActionPerformed

    private void but3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but3ActionPerformed
        // TODO add your handling code here:
         if(count%2==0 && but3.getIcon()==null){
        but3.setIcon(ovel);
        }
        else if(but3.getIcon()!=null){
            count--;
        }
        else if(but3.getIcon()==null){
            but3.setIcon(cross);
        }
        count++;
        select();
    }//GEN-LAST:event_but3ActionPerformed

    private void but4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but4ActionPerformed
        if(count%2==0 && but4.getIcon()==null){
        but4.setIcon(ovel);
        }
        else if(but4.getIcon()!=null){
            count--;
        }
        else if(but4.getIcon()==null){
            but4.setIcon(cross);
        }
        count++; 
        select();// TODO add your handling code here:
        
    }//GEN-LAST:event_but4ActionPerformed

    private void but5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but5ActionPerformed
        // TODO add your handling code here:
        if(count%2==0 && but5.getIcon()==null){
        but5.setIcon(ovel);
        }
        else if(but5.getIcon()!=null){
            count--;
        }
        else if(but5.getIcon()==null){
            but5.setIcon(cross);
        }
        count++;
        select();
    }//GEN-LAST:event_but5ActionPerformed

    private void but6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but6ActionPerformed
        // TODO add your handling code here:
         if(count%2==0 && but6.getIcon()==null){
        but6.setIcon(ovel);
        }
        else if(but6.getIcon()!=null){
            count--;
        }
        else if(but6.getIcon()==null){
            but6.setIcon(cross);
        }
        count++;
        select();
    }//GEN-LAST:event_but6ActionPerformed

    private void but7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but7ActionPerformed
        // TODO add your handling code here:
         if(count%2==0 && but7.getIcon()==null){
        but7.setIcon(ovel);
        }
        else if(but7.getIcon()!=null){
            count--;
        }
        else if(but7.getIcon()==null){
            but7.setIcon(cross);
        }
        count++;
        select();
    }//GEN-LAST:event_but7ActionPerformed

    private void but8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but8ActionPerformed
        // TODO add your handling code here:
         if(count%2==0 && but8.getIcon()==null){
        but8.setIcon(ovel);
        }
        else if(but8.getIcon()!=null){
            count--;
        }
        else if(but8.getIcon()==null){
            but8.setIcon(cross);
        }
        count++;
        select();
    }//GEN-LAST:event_but8ActionPerformed

    private void but9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but9ActionPerformed
        // TODO add your handling code here:
         if(count%2==0 && but9.getIcon()==null){
        but9.setIcon(ovel);
        }
        else if(but9.getIcon()!=null){
            count--;
        }
        else if(but9.getIcon()==null){
            but9.setIcon(cross);
        }
        count++;
        select();
    }//GEN-LAST:event_but9ActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        // TODO add your handling code here:
        but1.setIcon(null);
        but2.setIcon(null);
        but3.setIcon(null);
        but4.setIcon(null);
        but5.setIcon(null);
        but6.setIcon(null);
        but7.setIcon(null);
        but8.setIcon(null);
        but9.setIcon(null);
        score1.setText(String.valueOf(player1score));
       score2.setText(String.valueOf(player2score));
       count=0;
        

    }//GEN-LAST:event_ResetButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        new MultiPlayerDA().write(player1Name, player1score, player2Name, player2score);
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed
        public void select(){
            System.out.println(""+count);
        Icon icon = but1.getIcon();
            if((but1.getIcon()==ovel && but2.getIcon()==ovel && but3.getIcon()==ovel)||(but4.getIcon()==ovel && but5.getIcon()==ovel && but6.getIcon()==ovel)||(but7.getIcon()==ovel && but8.getIcon()==ovel && but9.getIcon()==ovel)){
                System.out.println(player1Name+" won the game");
                player1score++;
                JOptionPane.showMessageDialog(MultiPlayerGame.this, player1Name+" won the game","",JOptionPane.INFORMATION_MESSAGE,box);
               // player.setVisible(rootPaneCheckingEnabled);
               // player.setTitle("Tic Tac Toe");
               // player.setSize(330, 430);
               // setVisible(false);
            }else if ((but1.getIcon()==ovel && but4.getIcon()==ovel && but7.getIcon()==ovel)||(but2.getIcon()==ovel && but5.getIcon()==ovel && but8.getIcon()==ovel)||(but3.getIcon()==ovel && but6.getIcon()==ovel && but9.getIcon()==ovel)){
                System.out.println(player1Name+" won the game");
                player1score++;
                JOptionPane.showMessageDialog(MultiPlayerGame.this, player1Name+" won the game","",JOptionPane.INFORMATION_MESSAGE,box);
               // player.setVisible(rootPaneCheckingEnabled);
               // player.setTitle("Tic Tac Toe");
                //player.setSize(330,430);
               // setVisible(false);
            }else if((but1.getIcon()==ovel && but5.getIcon()==ovel && but9.getIcon()==ovel)||(but3.getIcon()==ovel && but5.getIcon()==ovel && but7.getIcon()==ovel)){
                System.out.println(player1Name+" won the game");
                player1score++;
                JOptionPane.showMessageDialog(MultiPlayerGame.this, player1Name+" won the game","",JOptionPane.INFORMATION_MESSAGE,box);
//                player.setVisible(rootPaneCheckingEnabled);
//                player.setTitle("Tic Tac Toe");
//                player.setSize(330,430);
//                setVisible(false);
            }else if((but1.getIcon()==cross && but5.getIcon()==cross && but9.getIcon()==cross)||(but3.getIcon()==cross && but5.getIcon()==cross && but7.getIcon()==cross)){
                System.out.println(player2Name+" won the game");
                player2score++;
                JOptionPane.showMessageDialog(MultiPlayerGame.this, player2Name+" won the game","",JOptionPane.INFORMATION_MESSAGE,box);
//                player.setVisible(rootPaneCheckingEnabled);
//                player.setTitle("Tic Tac Toe");
//                player.setSize(330,430);
//                setVisible(false);
            }else if ((but1.getIcon()==cross && but4.getIcon()==cross && but7.getIcon()==cross)||(but2.getIcon()==cross && but5.getIcon()==cross && but8.getIcon()==cross)||(but3.getIcon()==cross && but6.getIcon()==cross && but9.getIcon()==cross)){
                System.out.println(player2Name+" won the game");
                player2score++;
                JOptionPane.showMessageDialog(MultiPlayerGame.this, player2Name+" won the game","",JOptionPane.INFORMATION_MESSAGE,box);
//                player.setVisible(rootPaneCheckingEnabled);
//                player.setTitle("Tic Tac Toe");
//                player.setSize(330,430);
//                setVisible(false);
            }else if((but1.getIcon()==cross && but2.getIcon()==cross && but3.getIcon()==cross)||(but4.getIcon()==cross && but5.getIcon()==cross && but6.getIcon()==cross)||(but7.getIcon()==cross && but8.getIcon()==cross && but9.getIcon()==cross)){
                System.out.println(player2Name+" won the game");
                player2score++;
                JOptionPane.showMessageDialog(MultiPlayerGame.this, player2Name+" won the game","",JOptionPane.INFORMATION_MESSAGE,box);
//                player.setVisible(rootPaneCheckingEnabled);
//                player.setTitle("Tic Tac Toe");
//                player.setSize(330,430);
//                setVisible(false);
            }else if(count==9) {
                JOptionPane.showMessageDialog(MultiPlayerGame.this, "Game Tied","",JOptionPane.INFORMATION_MESSAGE,box);
                
//                player.setVisible(rootPaneCheckingEnabled);
//                player.setTitle("Tic Tac Toe");
//                player.setSize(330,430);
//                setVisible(false);
            }
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MultiPlayerGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MultiPlayerGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MultiPlayerGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MultiPlayerGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MultiPlayerGame().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ResetButton;
    private javax.swing.JButton but1;
    private javax.swing.JButton but2;
    private javax.swing.JButton but3;
    private javax.swing.JButton but4;
    private javax.swing.JButton but5;
    private javax.swing.JButton but6;
    private javax.swing.JButton but7;
    private javax.swing.JButton but8;
    private javax.swing.JButton but9;
    private javax.swing.JToggleButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel score1;
    private javax.swing.JLabel score2;
    // End of variables declaration//GEN-END:variables
}
